name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - altair=5.4.0=pyhd8ed1ab_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - arrow-cpp=10.0.1=h88f4db0_4_cpu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - atk-1.0=2.38.0=h4bec284_2
  - attrs=24.2.0=pyh71513ae_0
  - aws-c-auth=0.6.21=hbc0b158_0
  - aws-c-cal=0.5.20=hdc31e88_3
  - aws-c-common=0.8.5=hb7f2c08_0
  - aws-c-compression=0.2.16=hfb1f584_0
  - aws-c-event-stream=0.2.15=h6beef47_11
  - aws-c-http=0.6.27=h40fbe91_3
  - aws-c-io=0.13.11=hb3bb6ef_2
  - aws-c-mqtt=0.7.13=h95fd635_9
  - aws-c-s3=0.2.1=h9f2fa91_0
  - aws-c-sdkutils=0.1.7=hfb1f584_0
  - aws-checksums=0.1.13=hfb1f584_5
  - aws-crt-cpp=0.18.16=h8755ad4_2
  - aws-sdk-cpp=1.9.379=hafd40d4_5
  - blinker=1.8.2=pyhd8ed1ab_0
  - boost-cpp=1.84.0=hfcd56d9_5
  - brotli=1.0.9=hb7f2c08_9
  - brotli-bin=1.0.9=hb7f2c08_9
  - brotli-python=1.0.9=py39h7a8716b_9
  - bzip2=1.0.8=hfdf4475_7
  - c-ares=1.33.0=h51dda26_0
  - ca-certificates=2024.7.4=h8857fd0_0
  - cachetools=5.5.0=pyhd8ed1ab_0
  - cairo=1.18.0=h37bd5c4_3
  - catboost=1.2.5=py39h6e9494a_0
  - certifi=2024.7.4=pyhd8ed1ab_0
  - cffi=1.17.0=py39h3bee980_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.1=py39h0ca7971_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.5=py39h09c4c31_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h73e2aa4_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h5bb23bf_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py39hded5825_0
  - freetype=2.12.1=h60636b9_2
  - fribidi=1.0.10=hbcb3906_0
  - gdk-pixbuf=2.42.10=he00a9fc_0
  - gettext=0.22.5=hdfe23c8_3
  - gettext-tools=0.22.5=hdfe23c8_3
  - gflags=2.2.2=hb1e8313_1004
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - glog=0.6.0=h8ac2a54_0
  - graphite2=1.3.13=h73e2aa4_1003
  - graphviz=9.0.0=hee74176_1
  - gtk2=2.24.33=h8ca4665_4
  - gts=0.7.6=h53e17e3_4
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=9.0.0=h098a298_1
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=h120a0e1_0
  - idna=3.7=pyhd8ed1ab_0
  - imbalanced-learn=0.12.3=pyhd8ed1ab_0
  - importlib-metadata=7.2.1=pyha770c72_0
  - importlib-resources=6.4.3=pyhd8ed1ab_0
  - importlib_metadata=7.2.1=hd8ed1ab_0
  - importlib_resources=6.4.3=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.18.1=pyh707e725_3
  - ipywidgets=8.1.3=pyhd8ed1ab_0
  - jbig=2.1=h0d85af4_2003
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=hb7f2c08_3
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.1=py39h6e9494a_0
  - jupyterlab_widgets=3.0.11=pyhd8ed1ab_0
  - khronos-opencl-icd-loader=2023.04.17=h37ebe6b_1
  - kiwisolver=1.4.5=py39h8ee36c8_1
  - krb5=1.20.1=h049b76e_0
  - lcms2=2.15=h29502cd_0
  - lerc=4.0.0=hb486fe8_0
  - libabseil=20220623.0=cxx17_h844d122_6
  - libarrow=10.0.1=h5398121_4_cpu
  - libasprintf=0.22.5=hdfe23c8_3
  - libasprintf-devel=0.22.5=hdfe23c8_3
  - libblas=3.9.0=22_osx64_openblas
  - libboost=1.84.0=hcca3243_5
  - libboost-devel=1.84.0=h2b186f8_5
  - libboost-headers=1.84.0=h694c41f_5
  - libbrotlicommon=1.0.9=hb7f2c08_9
  - libbrotlidec=1.0.9=hb7f2c08_9
  - libbrotlienc=1.0.9=hb7f2c08_9
  - libcblas=3.9.0=22_osx64_openblas
  - libcrc32c=1.1.2=he49afe7_0
  - libcurl=8.1.2=hbee3ae8_0
  - libcxx=18.1.8=heced48a_4
  - libdeflate=1.17=hac1461d_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=h10d778d_2
  - libevent=2.1.10=h7d65743_4
  - libexpat=2.6.2=h73e2aa4_0
  - libffi=3.4.4=hecd8cb5_1
  - libgd=2.3.3=he7e2580_1
  - libgettextpo=0.22.5=hdfe23c8_3
  - libgettextpo-devel=0.22.5=hdfe23c8_3
  - libgfortran=5.0.0=13_2_0_h97931a8_3
  - libgfortran5=13.2.0=h2873a65_3
  - libglib=2.80.3=h736d271_2
  - libgoogle-cloud=2.5.0=hb5e37a9_1
  - libgrpc=1.51.1=h966d1d5_0
  - libiconv=1.17=hd75f5a5_2
  - libintl=0.22.5=hdfe23c8_3
  - libintl-devel=0.22.5=hdfe23c8_3
  - liblapack=3.9.0=22_osx64_openblas
  - libnghttp2=1.58.0=h64cf6d3_1
  - libopenblas=0.3.27=openmp_h8869122_1
  - libpng=1.6.43=h92b6c6a_0
  - libprotobuf=3.21.12=h7d26f99_2
  - librsvg=2.58.0=h7b06fc5_1
  - libsodium=1.0.18=hbcb3906_1
  - libsqlite=3.45.2=h92b6c6a_0
  - libssh2=1.11.0=hd019ec5_0
  - libthrift=0.16.0=h16802d8_2
  - libtiff=4.5.0=hee9004a_2
  - libutf8proc=2.8.0=hb7f2c08_0
  - libwebp-base=1.4.0=h10d778d_0
  - libxcb=1.13=h0d85af4_1004
  - libxgboost=2.1.1=cpu_h7ae7b8f_1
  - libxml2=2.12.7=heaf3512_4
  - libzlib=1.3.1=h87427d6_1
  - lightgbm=4.5.0=cpu_py3.9ha5fbf2f_1
  - llvm-openmp=18.1.8=h15ab845_1
  - lz4-c=1.9.4=hf0c8a7f_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py39ha09f3b3_0
  - matplotlib=3.9.2=py39h6e9494a_0
  - matplotlib-base=3.9.2=py39hb2d44f9_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - narwhals=1.4.2=pyhd8ed1ab_0
  - ncurses=6.4=hcec6c5f_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=1.26.4=py39h28c39a1_0
  - olefile=0.47=pyhd8ed1ab_0
  - openjpeg=2.5.0=h13ac156_2
  - openssl=3.3.1=h87427d6_2
  - orc=1.8.2=ha9d861c_2
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py39hbb604f3_1
  - pango=1.54.0=h115fe74_2
  - parquet-cpp=1.5.1=2
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.44=h7634a1b_2
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py39h7f5cd59_1
  - pip=24.2=py39hecd8cb5_0
  - pixman=0.43.4=h73e2aa4_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - plotly=5.23.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - protobuf=4.21.12=py39h7a8716b_0
  - psutil=6.0.0=py39hded5825_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - py-xgboost=2.1.1=cpu_pyh995e691_1
  - pyarrow=10.0.1=py39h2db5b05_4_cpu
  - pycparser=2.22=pyhd8ed1ab_0
  - pydeck=0.8.0=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.18=h7a9c478_1_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-graphviz=0.20.3=pyh717bed2_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py39hded5825_0
  - pyzmq=26.1.1=py39hf975025_0
  - qhull=2020.2=h3c5361c_5
  - re2=2022.06.01=hb486fe8_1
  - readline=8.2=hca72f7f_0
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rich=13.7.1=pyhd8ed1ab_0
  - rpds-py=0.20.0=py39hf59063a_0
  - scikit-learn=1.5.1=py39hf6a2366_0
  - scipy=1.13.1=py39h038d4f4_0
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - setuptools=72.1.0=py39hecd8cb5_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.10=h6dc393e_1
  - sqlite=3.45.2=h7461747_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.2=py39hb943cd9_0
  - streamlit=1.37.1=pyhd8ed1ab_0
  - tenacity=8.5.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=h1abcd95_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.4.1=py39hded5825_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h04d1e81_0
  - tzlocal=5.2=py39h6e9494a_0
  - unicodedata2=15.1.0=py39hdc70f33_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - utf8proc=2.6.1=h6c40b1e_1
  - validators=0.33.0=pyhd8ed1ab_0
  - watchdog=4.0.1=py39hded5825_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py39hecd8cb5_0
  - widgetsnbextension=4.0.11=pyhd8ed1ab_0
  - xgboost=2.1.1=cpu_pyhb8f9a19_1
  - xorg-libxau=1.0.11=h0dc2134_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xz=5.4.6=h6c40b1e_1
  - yaml=0.2.5=h0d85af4_2
  - zeromq=4.3.5=h93d8f39_0
  - zipp=3.20.0=pyhd8ed1ab_0
  - zlib=1.3.1=h87427d6_1
  - zstandard=0.23.0=py39h32d468b_0
  - zstd=1.5.6=h915ae27_0
prefix: /opt/anaconda3/envs/myenv
